services:
  jsf-app:
    build: .
    container_name: vitalnet-jsf-app
    ports:
      - "9000:8081"
    volumes:
      - ./src/main/liberty/config/server.xml:/config/server.xml:ro
    #restart: unless-stopped
    depends_on:
      - vitalnet

  vitalnet:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: vitaldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped


  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "9081:8080"
    depends_on:
      - vitalnet

volumes:
  pgdata:
